spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:weatherdb
  h2:
    console:
      enabled: true
weather-stack:
  api-url: http://api.weatherstack.com/current
  api-key: ef576d864633e9ebe3cde456c00cd2e4